name: PocAPI
services:
  pocapi:
    image: ${DOCKER_REGISTRY-}pocapi
    container_name: Poc-html2pdf.API
    build:
      context: PocApi
      dockerfile: Dockerfile
    ports:
      - "5001:8081"  # Map host port 5001 to container port 8081
    environment:
      - Gotenberg__BaseUrl=http://gotenberg:3000
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:8 # If no port is passed, it will be available in gotenberg:3000
    ports:
      - "3000:3000" # Api available on port http://localhost:3000
